import os
import openai
import json
import pandas as pd

openai.organization = "org-iKrZv1G3h27ngg6tO3rkCDlk"
openai.api_key = os.getenv("OPENAI_API_KEY")

# text = "Pre- Study	Cycle 1	Cycle 2	Cycle 3	Cycle 4	Cycle 5	Cycle 6	Treatment Discontinuation	Off Study1	Informed consent	SELECTED X	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED2	Demographics	SELECTED X	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED3	Medical history	SELECTED X	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED4	Physical exam	SELECTED X	SELECTED X	SELECTED X	SELECTED X	SELECTED X	SELECTED X	SELECTED X	SELECTED X	SELECTED X5	Vital signs	SELECTED X	SELECTED X	SELECTED X	SELECTED X	SELECTED X	SELECTED X	SELECTED X	SELECTED X	SELECTED X6	Height	SELECTED X	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED7	Weight	SELECTED X	NOT_SELECTED	NOT_SELECTED	SELECTED X	NOT_SELECTED	SELECTED X	NOT_SELECTED	SELECTED X	SELECTED X8	Biopsy diagnostic of KS (fixed in formalin)	SELECTED Xe	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED9	FACT-G Questionnaire	NOT_SELECTED	SELECTED Xf	NOT_SELECTED	NOT_SELECTED	SELECTED X	NOT_SELECTED	NOT_SELECTED	SELECTED X	SELECTED X10	Toxicity evaluations	NOT_SELECTED	SELECTED	SELECTED X	SELECTED X	SELECTED X	SELECTED X	SELECTED X	SELECTED X	SELECTED X11	Performance status	SELECTED X	SELECTED X	SELECTED X	SELECTED X	SELECTED X	SELECTED X	SELECTED X	SELECTED X	SELECTED X12	CBC w/diff, plts	SELECTED X	SELECTED X	SELECTED X	SELECTED X	SELECTED X	SELECTED X	SELECTED	SELECTED X	SELECTED X13	Serum chemistry	SELECTED X	SELECTED X	SELECTED X	SELECTED X	SELECTED X	SELECTED X	SELECTED X	SELECTED X	SELECTED X14	Oxygen saturation	SELECTED Xb	SELECTED X	SELECTED X	SELECTED X	SELECTED X	SELECTED X	SELECTED X	SELECTED X	SELECTED X15	Radiologic evaluation	SELECTED X	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED	NOT_SELECTED	SELECTED X	SELECTED X16	Tumor measurements	SELECTED X	NOT_SELECTED	SELECTED X	NOT_SELECTED	SELECTED X	NOT_SELECTED	SELECTED X	SELECTED X	SELECTED X17	Pregnancy test	SELECTED Xd	NOT_SELECTED	SELECTED X	SELECTED X	SELECTED X	SELECTED X	SELECTED X	NOT_SELECTED	NOT_SELECTED"
# text = 'Primary objective: Assess at week 12/16, post biologic treatment, the sensitivity and the specificity, compared to DLQI as a standard tool, of the PSO-TARGET QoL component grid as a novel approach aiming to evaluate the patients’ satisfaction with regard of their treatment.'

data = pd.read_csv('text.csv')
text = data.astype(str)
print(text.iloc[0][2])






# completion = openai.Completion.create(
  # model="text-davinci-003",
  # prompt=f"extract the validated clinical questionnaires used in this text:{text}",
  # max_tokens=4000,
  # temperature=0
# )
# print(completion["choices"][0]["text"])